"""Compile a paradigm + spec dict into a pure PsychoPy Python script.

Platform-agnostic entry: compile_spec(paradigm_id, spec) dispatches by id.
Output is a self-contained .py that runs under D:\\Software\\P\\python.exe.

Headless mode (env PSYCLAW_HEADLESS=1 or --headless argv):
  - windowed, no fullscr
  - no real keyboard wait; auto-inject responses so a server can run it
"""
from __future__ import annotations
from textwrap import dedent
from typing import Any, Dict


HEADER = '''\
#!/usr/bin/env python
"""Auto-generated by psyclaw-webui. Do not edit by hand.

Run with PsychoPy's Python:
  D:\\\\Software\\\\P\\\\python.exe this_script.py
  D:\\\\Software\\\\P\\\\python.exe this_script.py --headless
"""
import csv
import os
import sys
import time
from pathlib import Path

THIS_DIR = Path(__file__).resolve().parent
DATA_DIR = THIS_DIR / "data"
DATA_DIR.mkdir(exist_ok=True)

HEADLESS = ("--headless" in sys.argv) or (os.environ.get("PSYCLAW_HEADLESS", "0") == "1")

# Clear hermes pollution when launched from agent terminal
if "hermes" in (os.environ.get("VIRTUAL_ENV") or "").lower():
    pass  # parent already clears PYTHONPATH for us

from psychopy import core, event, visual  # noqa: E402
'''


def _window(spec: Dict[str, Any]) -> str:
    full = bool(spec.get("fullscreen", True))
    size = str(spec.get("screen_size", "1024x768")).lower().split("x")
    w, h = int(size[0]), int(size[1]) if len(size) > 1 else 768
    return dedent(f'''\
        if HEADLESS:
            win = visual.Window(size=(800, 600), fullscr=False, color=[-1, -1, -1],
                                units="height", allowGUI=False, winType="pyglet")
        else:
            win = visual.Window(size=({w}, {h}), fullscr={full}, color=[-1, -1, -1],
                                units="height", allowGUI=False)
    ''')


def _participant(spec: Dict[str, Any]) -> str:
    pid = str(spec.get("participant_id", "P01")).strip() or "P01"
    return dedent(f'''\
        participant_id = {pid!r}
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        out_csv = DATA_DIR / f"{{participant_id}}_{{timestamp}}.csv"
        rows = []
        print(f"[psyclaw] participant={{participant_id}} headless={{HEADLESS}} -> {{out_csv}}", flush=True)
    ''')


def _text_screen(label: str, text: str) -> str:
    return dedent(f'''\
        # {label}
        _t = visual.TextStim(win, text={text!r}, height=0.05, color=[1, 1, 1], wrapWidth=1.4)
        _t.draw(); win.flip()
        if HEADLESS:
            core.wait(0.3)
        else:
            event.waitKeys(keyList=["space"])
        del _t
    ''')


def _csv_footer() -> str:
    return dedent('''\
        if rows:
            with open(out_csv, "w", newline="", encoding="utf-8") as f:
                w = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
                w.writeheader()
                w.writerows(rows)
            print(f"[psyclaw] wrote {len(rows)} trials -> {out_csv}", flush=True)
        else:
            print("[psyclaw] no trials written", flush=True)
        win.close()
        core.quit()
    ''')


def compile_stroop(spec: Dict[str, Any]) -> str:
    n = int(spec.get("n_trials", 30))
    stim_ms = int(spec.get("stimulus_duration_ms", 1500))
    iti_ms = int(spec.get("iti_ms", 500))
    n_cong = int(spec.get("n_congruent", n // 2))
    n_incong = int(spec.get("n_incongruent", n - n_cong))
    instr = str(spec.get("instructions_text", "Welcome. Press SPACE to begin."))
    thanks = str(spec.get("thanks_text", "Thank you. Press SPACE to exit."))

    body = dedent(f'''\
        WORDS = ["RED", "GREEN", "BLUE", "YELLOW"]
        COLORS = {{"RED": [1, -1, -1], "GREEN": [-1, 1, -1], "BLUE": [-1, -1, 1], "YELLOW": [1, 1, -1]}}
        KEYMAP = {{"r": "RED", "g": "GREEN", "b": "BLUE", "y": "YELLOW"}}
        KEY_TO_INK = {{"r": "red", "g": "green", "b": "blue", "y": "yellow"}}

        import random
        rng = random.Random(42 if HEADLESS else None)
        trials = []
        # Build balanced list then shuffle
        for _ in range({n_cong}):
            w = rng.choice(WORDS)
            trials.append({{"word": w, "ink": w.lower(), "congruent": 1}})
        for _ in range({n_incong}):
            w = rng.choice(WORDS)
            inks = [c for c in COLORS if c != w]
            ink = rng.choice(inks).lower() if inks else w.lower()
            trials.append({{"word": w, "ink": ink, "congruent": 0}})
        while len(trials) < {n}:
            w = rng.choice(WORDS)
            trials.append({{"word": w, "ink": w.lower(), "congruent": 1}})
        trials = trials[:{n}]
        rng.shuffle(trials)

        stim = visual.TextStim(win, text="", height=0.15, color=[1, 1, 1])
        fix = visual.TextStim(win, text="+", height=0.08, color=[0.5, 0.5, 0.5])
        clock = core.Clock()

        for i, t in enumerate(trials):
            if {iti_ms} > 0:
                fix.draw(); win.flip()
                core.wait({iti_ms} / 1000.0)

            ink_name = t["ink"].upper()
            stim.text = t["word"]
            stim.color = COLORS.get(ink_name, [1, 1, 1])
            stim.draw(); win.flip()
            t0 = clock.getTime()

            if HEADLESS:
                # Auto-respond correctly ~80% of the time after a short RT
                core.wait(0.05)
                correct_key = t["ink"][0]  # r/g/b/y from ink color name
                if rng.random() < 0.8:
                    resp = correct_key
                else:
                    resp = rng.choice([k for k in KEYMAP if k != correct_key])
                rt = round(0.35 + rng.random() * 0.4, 4)
            else:
                keys = event.waitKeys(keyList=list(KEYMAP.keys()),
                                      maxWait={stim_ms} / 1000.0, timeStamped=True)
                t1 = clock.getTime()
                rt = (t1 - t0) if keys else None
                resp = keys[0][0] if keys else None

            resp_ink = KEY_TO_INK.get(resp) if resp else None
            correct = int(resp_ink == t["ink"]) if resp_ink else 0
            rows.append({{
                "trial": i + 1,
                "word": t["word"],
                "ink_color": t["ink"],
                "congruent": t["congruent"],
                "response": resp or "",
                "correct": correct,
                "rt": round(rt, 4) if rt is not None else "",
                "participant_id": participant_id,
            }})
            print(f"[psyclaw] trial {{i+1}} word={{t['word']}} ink={{t['ink']}} resp={{resp}} rt={{rt}}", flush=True)
    ''')

    return "\n".join([
        HEADER,
        _window(spec),
        _participant(spec),
        _text_screen("Instructions", instr),
        body,
        _text_screen("Thanks", thanks),
        _csv_footer(),
    ])


def compile_gonogo(spec: Dict[str, Any]) -> str:
    n_go = int(spec.get("n_go", 40))
    n_nogo = int(spec.get("n_nogo", 20))
    stim_ms = int(spec.get("stimulus_duration_ms", 250))
    iti_ms = int(spec.get("iti_ms", 1500))
    go_label = str(spec.get("go_label", "X"))
    nogo_label = str(spec.get("nogo_label", "O"))
    resp_key = str(spec.get("response_key", "space"))
    instr = str(spec.get("instructions_text", "Press SPACE on go. Do nothing on no-go."))
    thanks = str(spec.get("thanks_text", "Thank you."))

    body = dedent(f'''\
        import random
        rng = random.Random(42 if HEADLESS else None)
        trials = ([{{"kind": "go", "label": {go_label!r}}}] * {n_go}
                  + [{{"kind": "nogo", "label": {nogo_label!r}}}] * {n_nogo})
        rng.shuffle(trials)

        stim = visual.TextStim(win, text="", height=0.15, color=[1, 1, 1])
        fix = visual.TextStim(win, text="+", height=0.08, color=[0.5, 0.5, 0.5])
        clock = core.Clock()
        RESP_KEY = {resp_key!r}

        for i, t in enumerate(trials):
            if {iti_ms} > 0:
                fix.draw(); win.flip()
                core.wait({iti_ms} / 1000.0)

            stim.text = t["label"]
            stim.draw(); win.flip()
            t0 = clock.getTime()

            if HEADLESS:
                core.wait(0.05)
                if t["kind"] == "go":
                    # 90% hit, 10% miss
                    if rng.random() < 0.9:
                        resp = RESP_KEY
                        rt = round(0.25 + rng.random() * 0.3, 4)
                    else:
                        resp = None
                        rt = None
                else:
                    # 85% correct withhold, 15% false alarm
                    if rng.random() < 0.15:
                        resp = RESP_KEY
                        rt = round(0.2 + rng.random() * 0.2, 4)
                    else:
                        resp = None
                        rt = None
            else:
                keys = event.waitKeys(keyList=[RESP_KEY], maxWait={stim_ms} / 1000.0, timeStamped=True)
                t1 = clock.getTime()
                if keys:
                    resp = keys[0][0]
                    rt = t1 - t0
                else:
                    resp = None
                    rt = None

            if t["kind"] == "go":
                correct = int(resp is not None)
            else:
                correct = int(resp is None)

            rows.append({{
                "trial": i + 1,
                "kind": t["kind"],
                "label": t["label"],
                "response": resp or "",
                "correct": correct,
                "rt": round(rt, 4) if rt is not None else "",
                "participant_id": participant_id,
            }})
            print(f"[psyclaw] trial {{i+1}} kind={{t['kind']}} resp={{resp}} rt={{rt}}", flush=True)
    ''')

    return "\n".join([
        HEADER,
        _window(spec),
        _participant(spec),
        _text_screen("Instructions", instr),
        body,
        _text_screen("Thanks", thanks),
        _csv_footer(),
    ])


def compile_spec(paradigm_id: str, spec: Dict[str, Any]) -> str:
    pid = (paradigm_id or "").lower()
    if pid == "stroop":
        return compile_stroop(spec)
    if pid in ("gonogo", "go-no-go", "go_nogo"):
        return compile_gonogo(spec)
    return HEADER + dedent(f'''\
        print("[psyclaw] paradigm {pid!r} not implemented yet", flush=True)
        sys.exit(2)
    ''')
